[package]
name = "opencv-binding-generator"
description = "Binding generator for opencv crate"
repository = "https://github.com/twistedfall/opencv-rust"
version = "0.49.0"
license = "MIT"
authors = ["Pro <twisted.fall@gmail.com>"]
edition = "2018"

[lib]

[dependencies]
clang = {version = "2", features = ["clang_6_0"]}
clang-sys = {version = "1.0", features = ["clang_6_0"]}
dunce = "1"
maplit = "1"
once_cell = "1"
percent-encoding = "2"
regex = "1"
